name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git \
            openjdk-8-jdk \
            unzip \
            libunwind-dev

      - name: Install Cython
        run: pip install cython

      - name: Install Buildozer
        run: pip install --upgrade buildozer

      - name: Install Buildozer dependencies
        run: |
          sudo apt-get install -y \
            build-essential \
            ccache \
            git \
            libffi-dev \
            libssl-dev \
            libxml2-dev \
            libxslt1-dev \
            zlib1g-dev \
            python3-pip \
            python3-setuptools \
            python3-venv \
            python3-wheel \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            pkg-config \
            libgl1-mesa-dev \
            libgles2-mesa-dev \
            libgstreamer1.0-dev \
            libgstreamer-plugins-base1.0-dev \
            libnotify-dev \
            libtiff-dev \
            libjpeg-dev \
            libopenjp2-7-dev \
            libwebp-dev \
            libxcursor-dev \
            libxi-dev \
            libxrandr-dev \
            libxxf86vm-dev \
            liblzma-dev \
            libsqlite3-dev \
            libfontconfig1-dev \
            libxkbcommon-x11-dev \
            zlib1g-dev \
            libbz2-dev \
            libffi-dev \
            libssl-dev \
            libreadline-dev \
            libncursesw5-dev \
            libncurses5-dev \
            libsqlite3-dev \
            libgdbm-dev \
            tk-dev

      - name: Build APK
        run: buildozer -v android debug
